let paquetes = [
    {id:1 , nombre: "En medio de la magia", cantidad: 1, dias: 5, clase:"express", precio: 500, hotel: "no" , img: "../multimedia/imagenes/lentes-card.jpg",},
    {id: 2, nombre: "Disfruta a pleno", cantidad: 1, dias: 5, clase:"express", precio:600 , hotel: "no", img: "../multimedia/imagenes/ranas-card.jpg" },
    {id:3 , nombre: "Recorre la magia", cantidad: 1, dias:5, clase:"express", precio: 600, hotel: "no", img: "../multimedia/imagenes/auto-card.jpg" },
    {id: 4, nombre: "It's leviOsa", cantidad: 1, dias: 5, precio:800 , clase:"rest & meet",  hotel: "si", img: "../multimedia/imagenes/varitas-card.jpg"},
    {id:5 , nombre: "Escapada de fin de semana", cantidad: 1, dias:3, clase:"express", precio: 400, hotel: "no" , img: "../multimedia/imagenes/tren-card.jpg"},
    {id: 6,nombre: "No te pierdas de nada", cantidad: 1, dias: 7, clase:"rest & meet", precio: 800, hotel: "si" , img: "../multimedia/imagenes/varita-corbata-card.jpg"},
    {id:7 , nombre: "Enamorate de Hogwarts", cantidad: 1, dias:5, clase:"express", precio:500 ,  hotel: "no", img: "../multimedia/imagenes/varitayrosa-card.jpg"},
    {id:8 , nombre: "Tour gastronómico", cantidad: 1, dias:2, clase:"express", precio: 600,  hotel: "no", img: "../multimedia/imagenes/auto-card.jpg"},
    {id:9 , nombre: "All Inclusive", cantidad: 1, dias:9 , clase:"rest & meet", precio:1500 ,  hotel: "si", img: "../multimedia/imagenes/auto-card.jpg"},
    {id:10 , nombre: "Un día mágico", cantidad: 1, dias: 1, clase:"express", precio: 300, hotel: "no" , img: "../multimedia/imagenes/lentes-card.jpg"},
    {id:11, nombre: "Tour de compras. Un box de regalos para vos", cantidad: 1, dias: 3, clase:"rest & meet", precio:600 , hotel: "si", img: "../multimedia/imagenes/ranas-card.jpg" },
    {id:12, nombre: "Vuelo de escobas", cantidad: 1, dias:3, clase:"express", precio: 600, hotel: "no", img: "../multimedia/imagenes/auto-card.jpg" },
    {id:13, nombre: "Ranas de Chocolate", cantidad: 1, dias: 5, precio:800 , clase:"rest & meet",  hotel: "si", img: "../multimedia/imagenes/varitas-card.jpg"},
    {id:14 , nombre: "Paquete cinéfilo", cantidad: 1, dias:7, clase:"rest & meet", precio: 1200, hotel: "si" , img: "../multimedia/imagenes/tren-card.jpg"},
    {id: 15,nombre: "La magia de viajar", cantidad: 1, dias: 7, clase:"rest & meet", precio: 800, hotel: "si" , img: "../multimedia/imagenes/varita-corbata-card.jpg"},
    {id:16, nombre: "Curiosidades que te interesarían", cantidad: 1, dias:5, clase:"express", precio:500 ,  hotel: "no", img: "../multimedia/imagenes/varitayrosa-card.jpg"},
    {id:17 , nombre: "Estudios de grabación (disneyland)", cantidad: 1, dias:2, clase:"express", precio: 600,  hotel: "no", img: "../multimedia/imagenes/auto-card.jpg"},
    {id:18 , nombre: "Full pack", cantidad: 1, dias:14 , clase:"rest & meet", precio:2800 ,  hotel: "si", img: "../multimedia/imagenes/auto-card.jpg"},
]